Repository likelion-hackton/backend, pull requests merged in 2024-09, with the labels that each got.

#22 [FEATURE] 내 정보 조회 및 수정
  src/main/java/com/example/backend/common/config/WebConfig.java
  src/main/java/com/example/backend/common/jwt/JwtTokenFilter.java
  src/main/java/com/example/backend/common/security/SecurityConfig.java
  src/main/java/com/example/backend/member/controller/MemberController.java
  src/main/java/com/example/backend/member/converter/MemberConverter.java
  src/main/java/com/example/backend/member/entity/Member.java
  src/main/java/com/example/backend/memberInfo/controller/MemberInfoController.java
  src/main/java/com/example/backend/memberInfo/converter/MemberInfoConverter.java
  src/main/java/com/example/backend/memberInfo/entity/MemberInfo.java
  src/main/java/com/example/backend/memberInfo/entity/MemberInfoImage.java
  src/main/java/com/example/backend/memberInfo/entity/dto/request/EditMemberInfoRequestDTO.java
  src/main/java/com/example/backend/memberInfo/entity/dto/response/MemberInfoDetailResponseDTO.java
  src/main/java/com/example/backend/memberInfo/repository/MemberInfoImageRepository.java
  src/main/java/com/example/backend/memberInfo/repository/MemberInfoRepository.java
  src/main/java/com/example/backend/memberInfo/service/MemberInfoService.java
  src/main/java/com/example/backend/storage/service/StorageService.java
Labels: feature

#24 [FEATURE] 강의 참가 및 강의 전체 조회, 내 강의 조회 개발
  src/main/java/com/example/backend/lecture/controller/LectureController.java
  src/main/java/com/example/backend/lecture/converter/LectureConverter.java
  src/main/java/com/example/backend/lecture/entity/dto/request/JoinLectureRequestDTO.java
  src/main/java/com/example/backend/lecture/entity/dto/response/LectureListResponseDTO.java
  src/main/java/com/example/backend/lecture/service/LectureService.java
  src/main/java/com/example/backend/participant/converter/ParticipantConverter.java
  src/main/java/com/example/backend/participant/repository/ParticipantRepository.java
Labels: feature

#29 [feat] : Swagger-UI 에 Auth 버튼 추가
  src/main/java/com/example/backend/common/config/SwaggerConfig.java
Labels: feature

#36 [FEATURE] 비밀번호 변경 개발
  src/main/java/com/example/backend/member/controller/MemberController.java
  src/main/java/com/example/backend/member/converter/MemberConverter.java
  src/main/java/com/example/backend/member/entity/dto/request/ChangePwRequestDTO.java
  src/main/java/com/example/backend/member/service/MemberService.java
  src/main/java/com/example/backend/memberInfo/converter/MemberInfoConverter.java
  src/main/java/com/example/backend/memberInfo/entity/dto/response/MemberInfoDetailResponseDTO.java
Labels: feature

#39 [FEATURE] 강의 API 구분
  src/main/java/com/example/backend/lecture/controller/LectureController.java
  src/main/java/com/example/backend/lecture/converter/LectureConverter.java
  src/main/java/com/example/backend/lecture/entity/Lecture.java
  src/main/java/com/example/backend/lecture/entity/OneDayLecture.java
  src/main/java/com/example/backend/lecture/entity/RegularLecture.java
  src/main/java/com/example/backend/lecture/entity/dto/request/CreateLectureRequestDTO.java
  src/main/java/com/example/backend/lecture/entity/dto/request/CreateOneDayLectureRequestDTO.java
  src/main/java/com/example/backend/lecture/entity/dto/request/CreateRegularLectureRequestDTO.java
  src/main/java/com/example/backend/lecture/entity/dto/response/LectureDetailResponseDTO.java
  src/main/java/com/example/backend/lecture/entity/dto/response/LectureListResponseDTO.java
  src/main/java/com/example/backend/lecture/service/LectureService.java
  src/main/java/com/example/backend/member/entity/dto/request/SignupRequestDTO.java
  src/main/java/com/example/backend/member/service/MemberService.java
Labels: feature

#40 [FEATURE] 도로명 주소 위도 경도로 변환
  build.gradle
  src/main/java/com/example/backend/common/config/WebClientConfig.java
  src/main/java/com/example/backend/lecture/converter/LectureConverter.java
  src/main/java/com/example/backend/lecture/entity/Lecture.java
  src/main/java/com/example/backend/lecture/entity/dto/request/CreateLectureRequestDTO.java
  src/main/java/com/example/backend/lecture/entity/dto/response/LectureDetailResponseDTO.java
  src/main/java/com/example/backend/lecture/service/LectureService.java
Labels: feature

#41 Feature/#37 chat entity create
  src/main/java/com/example/backend/chat/entity/ChatMessage.java
  src/main/java/com/example/backend/chat/entity/ChatParticipant.java
  src/main/java/com/example/backend/chat/entity/ChatRoom.java
  src/main/java/com/example/backend/common/enums/ChatRoomStatus.java
Labels: feature

#43 [Fix] 내 정보 수정 이미지 버그 및 강의 이미지 수정
  src/main/java/com/example/backend/lecture/controller/LectureController.java
  src/main/java/com/example/backend/lecture/converter/LectureConverter.java
  src/main/java/com/example/backend/lecture/entity/dto/response/LectureDetailResponseDTO.java
  src/main/java/com/example/backend/lecture/entity/dto/response/LectureListResponseDTO.java
  src/main/java/com/example/backend/lecture/service/LectureService.java
  src/main/java/com/example/backend/memberInfo/controller/MemberInfoController.java
  src/main/java/com/example/backend/memberInfo/entity/dto/request/EditMemberInfoRequestDTO.java
Labels: bug

#45 [FEATURE] 카테고리 생성 및 카테고리 검색 개발
  src/main/java/com/example/backend/category/Category.java
  src/main/java/com/example/backend/lecture/controller/LectureController.java
  src/main/java/com/example/backend/lecture/converter/LectureConverter.java
  src/main/java/com/example/backend/lecture/entity/Lecture.java
  src/main/java/com/example/backend/lecture/entity/dto/request/CreateLectureRequestDTO.java
  src/main/java/com/example/backend/lecture/entity/dto/response/LectureDetailResponseDTO.java
  src/main/java/com/example/backend/lecture/repository/LectureRepository.java
  src/main/java/com/example/backend/lecture/service/LectureService.java
Labels: feature

#47 Feature/#38 채팅방 생성하기기능
  src/main/java/com/example/backend/chat/controller/ChatController.java
  src/main/java/com/example/backend/chat/converter/ChatConverter.java
  src/main/java/com/example/backend/chat/entity/ChatMessage.java
  src/main/java/com/example/backend/chat/entity/ChatRoom.java
  src/main/java/com/example/backend/chat/entity/ChatRoomMember.java
  src/main/java/com/example/backend/chat/entity/dto/MessageInfoDTO.java
  src/main/java/com/example/backend/chat/entity/dto/request/CreateChatRoomRequestDTO.java
  src/main/java/com/example/backend/chat/entity/dto/response/ChatRoomInfoResponseDTO.java
  src/main/java/com/example/backend/chat/repository/ChatRoomMemberRepository.java
  src/main/java/com/example/backend/chat/repository/ChatRoomRepository.java
  src/main/java/com/example/backend/chat/service/ChatService.java
  src/main/java/com/example/backend/common/enums/MessageType.java
  src/main/java/com/example/backend/participant/repository/ParticipantRepository.java
Labels: feature

#50 Feature/#48 message send
  src/main/java/com/example/backend/chat/controller/ChatController.java
  src/main/java/com/example/backend/chat/converter/ChatConverter.java
  src/main/java/com/example/backend/chat/entity/dto/request/SendChatMessageRequest.java
  src/main/java/com/example/backend/chat/repository/ChatMessageRepository.java
  src/main/java/com/example/backend/chat/repository/ChatRoomMemberRepository.java
  src/main/java/com/example/backend/chat/service/ChatService.java
Labels: feature

#52 Feature/#51 유저별 채팅방 전체조회
  src/main/java/com/example/backend/chat/controller/ChatController.java
  src/main/java/com/example/backend/chat/converter/ChatConverter.java
  src/main/java/com/example/backend/chat/entity/dto/ChatRoomInfoDTO.java
  src/main/java/com/example/backend/chat/entity/dto/response/ChatRoomAllResponseDTO.java
  src/main/java/com/example/backend/chat/repository/ChatMessageRepository.java
  src/main/java/com/example/backend/chat/repository/ChatRoomMemberRepository.java
  src/main/java/com/example/backend/chat/service/ChatService.java
Labels: feature

#54 Feature/#53 채팅방 상세보기
  src/main/java/com/example/backend/chat/controller/ChatController.java
  src/main/java/com/example/backend/chat/converter/ChatConverter.java
  src/main/java/com/example/backend/chat/entity/dto/ChatRoomInfoDTO.java
  src/main/java/com/example/backend/chat/repository/ChatRoomMemberRepository.java
  src/main/java/com/example/backend/chat/service/ChatService.java
Labels: feature

#56 [Feature] 지도 api 작성
  src/main/java/com/example/backend/lecture/controller/LectureController.java
  src/main/java/com/example/backend/lecture/converter/LectureConverter.java
  src/main/java/com/example/backend/lecture/entity/dto/response/LectureMapResponseDTO.java
  src/main/java/com/example/backend/lecture/service/LectureService.java
  src/main/java/com/example/backend/participant/repository/ParticipantRepository.java
Labels: feature

#57 [hotfix] : 채팅방 생성시 오류 발생 수정
  src/main/java/com/example/backend/participant/repository/ParticipantRepository.java
Labels: bug

#58 [hotfix] : @RequestParam 오류 수정
  src/main/java/com/example/backend/chat/controller/ChatController.java
Labels: bug

#59 [hotfix] : ParticipantRepository 에서 여러개 검색 되는 기능 한개만 검색되게 수정
  src/main/java/com/example/backend/chat/service/ChatService.java
  src/main/java/com/example/backend/participant/repository/ParticipantRepository.java
Labels: bug

#62 [fix] : 채팅방 전체보기에서 내 프로필 사진/채팅방 상대 프로필사진 같은 이미지로 보이는 오류 수정
  src/main/java/com/example/backend/chat/converter/ChatConverter.java
  src/main/java/com/example/backend/chat/service/ChatService.java
Labels: bug

#64 [FEATURE] Banner Response DTO 수정
  src/main/java/com/example/backend/lecture/converter/LectureConverter.java
  src/main/java/com/example/backend/lecture/entity/dto/response/LectureBannerResponseDTO.java
Labels: feature

#68 [fix] : ReviewController reqeustParam 수정
  src/main/java/com/example/backend/review/controller/ReviewController.java
Labels: bug

#71 FEAT/#63 chat message 읽음기능추가
  src/main/java/com/example/backend/chat/converter/ChatConverter.java
  src/main/java/com/example/backend/chat/entity/ChatMessage.java
  src/main/java/com/example/backend/chat/service/ChatService.java
Labels: feature

#69 [FEATURE] Lecture Join 예외처리
  src/main/java/com/example/backend/lecture/controller/LectureController.java
  src/main/java/com/example/backend/lecture/converter/LectureConverter.java
  src/main/java/com/example/backend/lecture/entity/dto/response/LectureDetailResponseDTO.java
  src/main/java/com/example/backend/lecture/service/LectureService.java
  src/main/java/com/example/backend/participant/converter/ParticipantConverter.java
  src/main/java/com/example/backend/participant/entity/Participant.java
  src/main/java/com/example/backend/participant/repository/ParticipantRepository.java
Labels: feature

#74 FEATURE/ #65 ChatService 검증 로직 추가
  src/main/java/com/example/backend/chat/service/ChatService.java
Labels: feature

#77 [Fix] 강의 상세 별점 수정
  src/main/java/com/example/backend/lecture/converter/LectureConverter.java
Labels: bug

#81 Feature/#70 채팅방삭제
  src/main/java/com/example/backend/chat/controller/ChatController.java
  src/main/java/com/example/backend/chat/repository/ChatMessageRepository.java
  src/main/java/com/example/backend/chat/repository/ChatRoomMemberRepository.java
  src/main/java/com/example/backend/chat/service/ChatService.java
Labels: feature

#84 [fix] : like/dislike API 수정
  src/main/java/com/example/backend/review/controller/ReviewController.java
  src/main/java/com/example/backend/review/service/ReviewService.java
Labels: feature

#86 [fix] : 리뷰 이미지 null 일때 400 에러 수정
  src/main/java/com/example/backend/review/controller/ReviewController.java
  src/main/java/com/example/backend/review/service/ReviewService.java
Labels: bug

#85 [FEATURE] 토큰 예외처리
  src/main/java/com/example/backend/common/jwt/JwtTokenFilter.java
Labels: feature

#88 [Fix] 문제 해결
  src/main/java/com/example/backend/common/jwt/JwtTokenFilter.java
Labels: bug

#89 [FEATURE] 강의 삭제 구현
  src/main/java/com/example/backend/lecture/controller/LectureController.java
  src/main/java/com/example/backend/lecture/service/LectureService.java
Labels: feature

#92 [REFACTOR] 이미지 수정 메소드 로직 수정
  src/main/java/com/example/backend/lecture/repository/LectureImageRepository.java
  src/main/java/com/example/backend/lecture/service/LectureService.java
Labels: refactor

#94 [FEATURE] Cascade 설정
  src/main/java/com/example/backend/lecture/entity/Lecture.java
Labels: feature

#96 [fix] : 같은 멤버들간 다른 클래스에 해당하는 채팅방 생성 안되는 오류 수정
  src/main/java/com/example/backend/chat/entity/ChatRoom.java
  src/main/java/com/example/backend/chat/repository/ChatRoomMemberRepository.java
  src/main/java/com/example/backend/chat/repository/ChatRoomRepository.java
  src/main/java/com/example/backend/chat/service/ChatService.java
Labels: bug
